version: '3.9'
services: 
  ros-basler:
    container_name: new-ros-basler
    image: gsavle/reconcycle:ros-basler
    environment:
      - ROS_MASTER_URI=http://10.20.0.1:11311
      - ROS_IP=10.20.0.2
      - "DISPLAY=$DISPLAY"
    network_mode: host
    restart: "no"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "(sleep 5 && rosservice call /basler/set_sleeping False) & roslaunch pylon_camera pylon_colour_camera_node.launch enable_current_params_publisher:=false" 
    privileged: true

